### ISSUE TITLE
Cannot invoke method getNextNumber() on null object

### ISSUE THREAD

**Issue by confile** [lmivan/grails-url-shortener#6]
I tried the following controller action: 

```
  def urlShortenerService


  def lala() {

    println "urlShortenerService: "+urlShortenerService
    
    String shortUrl = urlShortenerService.shortUrl("http://kaleidos.net")
    println "shortUrl: "+shortUrl

    render "OK"
  }
```

and got the following error: 

```
2015-01-16 18:47:22,511 [http-nio-8080-exec-5] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /test/home/lala
Cannot invoke method getNextNumber() on null object. Stacktrace follows:
Message: Cannot invoke method getNextNumber() on null object
    Line | Method
->>   48 | shortUrl           in net.kaleidos.shortener.UrlShortenerService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     68 | shortUrlFullDomain in     ''
|     25 | lala . . . . . . . in test.HomeController$$EP1YPA88
|    198 | doFilter           in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter           in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     49 | doFilter . . . . . in grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter
|     82 | doFilter           in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|     46 | doFilterInternal . in org.grails.jaxrs.web.JaxrsFilter
|   1142 | runWorker          in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                in java.lang.Thread
......
```

**Comment by lmivan** [comment]
I've just seen the problem. It has to do with the PR #3 merged a week ago. I'm going to update the documentation to make it much more clear how to configure the plugin.

@goeh Can you explain us why did you removed the definition of the default sequence generator?
https://github.com/lmivan/grails-url-shortener/pull/3/files#diff-78dc4227514a417abec5a2d3bf046037L52

In the mean time you need to provide your `sequenceGenerator` bean implementation. You have 3 different options:

1. Use the default sequenceGenerator that the plugin provides. You *should* only use it for tests because it's an in-memory implementation and when you restart your app the sequence will start by 1.
To do this, just define this bean in your `resources.groovy` file:
```
beans = {
    ...
    sequenceGenerator(net.kaleidos.shortener.generator.DummySequenceGenerator)
    ...
}
```

2. Use the `sequence-generator` plugin as it's explained in the README: https://github.com/lmivan/grails-url-shortener#sequence-generator-plugin

3. Implement and define you own sequenceGenerator. For example, if you are using Postgresql as database you can use the `PostgresSequenceGenerator.groovy` example in the README.

**Comment by goeh** [comment]
Leaving the default sequence generator in doWithSpring caused problems with overriding the bean. But I have to do some research to find out exactly what the problem was. I will let you know later today.
I'm very sorry that I missed this. The dummy generator is defined in the plugin's resources.groovy and in my test application so I did not notice.

**Comment by lmivan** [comment]
Don't worry, this things happens. I should have tested the plugin with a fresh app before release the 0.2 version but I only run the tests, so it's my fault :-(

As there's a workaround, don't worry to much. Enjoy the weekend :-)

**Comment by goeh** [comment]
I could not find a problem with adding back the default/dummy sequence generator in doWithSpring. 

During development of version 0.2 I removed it from the plugin descriptor and placed in in resources.groovy. I later found a better implementation but forgot to move it back.

I created a pull request to fix this. The fix is tested in two applications that uses url-shortener and they worked ok.

**Comment by lmivan** [comment]
Thank you very much. I have merged the PR and tried to publish the new version but it seems that there's a problem with grails server. I'll try it later...

**Comment by lmivan** [comment]
I finally published the plugin. The version 0.2.1 fix the problem.

Thank you very much @goeh

**Comment by lmivan** [comment]
@confile I've also update the documentation detailing that the default sequence generator shouldn't be used in production.
